#!/bin/sh /etc/rc.common

START=88

USE_PROCD=1
NAME=homed-zigbee
PROG=/usr/bin/homed-zigbee

start_service() {
	procd_open_instance
	procd_set_param command "$PROG"
	procd_close_instance
}

reload_service() {
	procd_send_signal $PROG
}
