#!/bin/sh /etc/rc.common

START=88

USE_PROCD=1
NAME=homed-zigbee
PROG=/usr/bin/homed-zigbee

start_service() {
	procd_open_instance
	procd_set_param command $PROG
	procd_set_param respawn ${respawn_threshold:-3600} ${respawn_timeout:-5} ${respawn_retry:-5}
	procd_close_instance
}

reload_service() {
	procd_send_signal $PROG
}
